"""Added new post column

Revision ID: 130dec983ef3
Revises: 7e7b0b29f37d
Create Date: 2022-09-21 20:22:53.538497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130dec983ef3'
down_revision = '7e7b0b29f37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'date_created')
    # ### end Alembic commands ###
